### ISSUE TITLE
WorkloadMetaCollector panics in agent version 7.33.0

### ISSUE THREAD

**Issue by deadok22** [DataDog/datadog-agent#10716]
The agent version 7.33.0 panics sporadically with the following trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x31bc00b]

goroutine 285 [running]:
github.com/DataDog/datadog-agent/pkg/tagger/collectors.(*WorkloadMetaCollector).processEvents(0xc00025ba70, 0xc000222780, 0xd, 0xd, 0xc0036c5680)
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/collectors/workloadmeta_extract.go:109 +0xcb
github.com/DataDog/datadog-agent/pkg/tagger/collectors.(*WorkloadMetaCollector).Stream(0xc00025ba70, 0xc, 0xc000d9abc8)
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/collectors/workloadmeta_main.go:103 +0x199
created by github.com/DataDog/datadog-agent/pkg/tagger/local.(*Tagger).registerCollectors
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/local/tagger.go:208 +0x1ec

```

**Comment by hit0ri** [comment]
Mine looks similar:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x27778b7]

goroutine 249 [running]:
github.com/DataDog/datadog-agent/pkg/workloadmeta.(*store).handleEvents(0xc0000bca00, 0xc000884b00, 0x11, 0x11)
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/workloadmeta/store.go:387 +0xb7
github.com/DataDog/datadog-agent/pkg/workloadmeta.(*store).Start.func1(0xc0000bca00, 0x5155480, 0xc00011c010)
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/workloadmeta/store.go:119 +0x185
created by github.com/DataDog/datadog-agent/pkg/workloadmeta.(*store).Start
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/workloadmeta/store.go:112 +0x57
```

**Comment by deadok22** [comment]
https://github.com/DataDog/datadog-agent/pull/10804 should fix it

**Comment by therc** [comment]
Any idea when 7.34 will be out? Ours on 7.33.1 is almost identical:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x31bc02b]

goroutine 396 [running]:
github.com/DataDog/datadog-agent/pkg/tagger/collectors.(*WorkloadMetaCollector).processEvents(0xc0004030e0, 0xc00112cd20, 0x5, 0x5, 0xc002eb4000)
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/collectors/workloadmeta_extract.go:109 +0xcb
github.com/DataDog/datadog-agent/pkg/tagger/collectors.(*WorkloadMetaCollector).Stream(0xc0004030e0, 0xc, 0xc0008f3048)
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/collectors/workloadmeta_main.go:103 +0x199
created by github.com/DataDog/datadog-agent/pkg/tagger/local.(*Tagger).registerCollectors
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/local/tagger.go:208 +0x1ec
```

**Comment by deadok22** [comment]
Hey @therc are you sure you're on 7.33.1? The fix was backported to the 7.33.x branch and included in the release (see https://github.com/DataDog/datadog-agent/commits/7.33.x). I've upgraded with no issues.

**Comment by therc** [comment]
@deadok22 we're definitely on 7.33.1.
```
2022-03-01 19:41:18 UTC | CORE | INFO | (cmd/agent/app/run.go:250 in StartAgent) | Starting Datadog Agent v7.33.1
# ls -l `which agent`
-rwxr-xr-x 1 root root 109069416 Feb 10 10:57 /opt/datadog-agent/bin/agent//agent
```
 It's a custom image with the nvml extra integration baked in... I wonder if that might be the problem. Or maybe it's a related, but not identical issue? I'll try with 7.34.0.

**Comment by b4b4r07** [comment]
Hi, thank you for reporting this issue.

We're facing on this too.
Is this solved on 7.34.0? We're using 7.33.1 but it's still happened on its version.

**Comment by deadok22** [comment]
>  I've upgraded with no issues.

I take this back. Some of my agent instances panic with this trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x31bc02b]

goroutine 335 [running]:
github.com/DataDog/datadog-agent/pkg/tagger/collectors.(*WorkloadMetaCollector).processEvents(0xc001cdefc0, 0xc000ff2000, 0x1b, 0x1b, 0xc00e7c1aa0)
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/collectors/workloadmeta_extract.go:109 +0xcb
github.com/DataDog/datadog-agent/pkg/tagger/collectors.(*WorkloadMetaCollector).Stream(0xc001cdefc0, 0xc, 0xc000e7f288)
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/collectors/workloadmeta_main.go:103 +0x199
created by github.com/DataDog/datadog-agent/pkg/tagger/local.(*Tagger).registerCollectors
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/local/tagger.go:208 +0x1ec
```

**Comment by therc** [comment]
Still there in 7.35.1, similar to @hit0ri 's, but not our previous stack trace:
```
2022-05-13 16:47:46 UTC | CORE | WARN | (pkg/workloadmeta/collectors/docker/docker.go:147 in generateEventsFromContainerList) | could not inspect container "57e87b2163036b874c02d4823338f6d85cde112b2e39d3ab751a1271adf4c782": Get "http://%!F(MISSING)host%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.40/containers/57e87b2163036b874c02d4823338f6d85cde112b2e39d3ab751a1271adf4c782/json": context deadline exceeded
2022-05-13 16:47:51 UTC | CORE | WARN | (pkg/workloadmeta/collectors/docker/docker.go:147 in generateEventsFromContainerList) | could not inspect container "024f53d01821a7b787e8efd9156daffc9affbcd332503a527fa5ea46350cbdd0": Get "http://%!F(MISSING)host%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.40/containers/024f53d01821a7b787e8efd9156daffc9affbcd332503a527fa5ea46350cbdd0/json": context deadline exceeded
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x263bfda]

goroutine 356 [running]:
github.com/DataDog/datadog-agent/pkg/workloadmeta.(*store).handleEvents(0xc0000f2d80, {0xc000844b40, 0xd, 0xd})
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/workloadmeta/store.go:364 +0x8da
github.com/DataDog/datadog-agent/pkg/workloadmeta.(*store).Start.func1()
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/workloadmeta/store.go:89 +0x157
created by github.com/DataDog/datadog-agent/pkg/workloadmeta.(*store).Start
	/omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/workloadmeta/store.go:82 +0x9a
```

**Comment by deadok22** [comment]
I took another look at the places where `workloadmeta.Event` are created and found this commit: https://github.com/DataDog/datadog-agent/commit/c06e23fe5103163b628954c6791273315a0859c6

The commit message says:
```
It's possible that `merge` returns a `nil` entity if the sources present
in `filteredSources` have also been deleted. This prevents the
generation of a `EventTypeSet` with a `nil` entity, and sends an
`EventTypeUnset` instead.
```

While [this line](https://github.com/DataDog/datadog-agent/commit/c06e23fe5103163b628954c6791273315a0859c6#diff-6ed7857f2afad2e0b2b69a81ac6dcda1e94a5a489dab1b7b6932501d91de2c83R452) does not do what the commit message says. @juliogreff could you have a look at it? Should the condition be changed to `if ev.Type == EventTypeSet && entity != nil`  instead?

**Comment by juliogreff** [comment]
@deadok22 follow up PRs changed it again, see #11200 where we actually found the root cause. It appears that this issue doesn't stem from that, see below.

@therc I don't see from the stack trace where a nil `subscribers` could be the issue, since it's pointing to a `meta := ev.Entity.GetID()` that doesn't involve subscribers at all.

Seems to be a missing `continue` in the docker collector on error: https://github.com/DataDog/datadog-agent/blob/main/pkg/workloadmeta/collectors/internal/docker/docker.go#L146-L148 -- I'll open a PR with a fix.

**Comment by therc** [comment]
@juliogreff in my last stack trace, the bad memory access is triggered at line 364. This is similar to the one seen by @hit0ri and not the one I posted initially.

**Comment by therc** [comment]
I don't see the GetID() call at https://github.com/DataDog/datadog-agent/blob/main/pkg/workloadmeta/store.go#L364

**Comment by juliogreff** [comment]
If you're using 7.35.1, this is the code you should be looking at: https://github.com/DataDog/datadog-agent/blob/7.35.1/pkg/workloadmeta/store.go#L364 -- main is now quite different
