### ISSUE TITLE
Logs dissapear after a while when using dd-trace +4 and serverless-init 1.1.1 in Cloud Run

### ISSUE THREAD

**Issue by abarone-btf** [DataDog/datadog-agent#20076]
Hi all, this is a really weird behavior I start noticing. The logs from my cloud run instances suddently stop appearing in the Cloud Logging view (using dd-trace 4.16.0 and serverless-init 1.1.1)

Its weird because when I restart the instance the logs start appearing again without any issue, but after some hours new logs are never shown until I restart the instance again.

I even try `console.log` (am using Node 18) for every request inside the instance to test, but even that log dissapear.

I've been debugging this behavior for almost a week, and recently try to remove everything form datadog and the logs never dissapear again.

Maybe something happend in the newer version of dd-trace or the newer version of the serverless-init image that all of the sudden starts "eating" the logs made to stdout.

Some images to show the behavior, the first is when everything works, the logs are showing up on the stackdriver panel:
![everything-ok](https://github.com/DataDog/dd-trace-js/assets/133253254/66810b70-bc10-4e5a-8711-3e1a8c5d659c)

After sometime, the logs made from my instance never appear again, only showing the default Cloud Run request log:
![after-some-time](https://github.com/DataDog/dd-trace-js/assets/133253254/9f2e5824-a033-4bcb-bed2-3665bd1b9a74)

Here are the env variables that my cloud run is using:
```
DD_SERVICE: some-service-name 
DD_ENV: some-env   
DD_VERSION: 0.0.1
DD_LOGS_ENABLED: true
DD_TRACE_TELEMETRY_ENABLED: false 
DD_APPSEC_ENABLED: true
---
DD_API_KEY: using secret manager integration, injected as env variable
```

This is a duplicate bug created in the `dd-trace` repo (https://github.com/DataDog/dd-trace-js/issues/3704)

Thanks for any help!

**Comment by abarone-btf** [comment]
I put the `debug` level on the agent and notice a lot of this warning message:
```
Could not send payload: Post "https://http-intake.logs.datadoghq.com/api/v2/logs": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

then this one:
```
https://http-intake.logs.datadoghq.com/api/v2/logs: sleeping until 2023-10-12 17:42:15.257829163 +0000 UTC m=+14870.489633979 before retrying. Backoff duration 100ms due to 7138 errors
```

Am I supposed to do something for that tls to work with cloud run?

**Comment by abarone-btf** [comment]
I can confirm that the `serverless-init:beta4` version does not have this behavior and the logs never dissapear

**Comment by abarone-btf** [comment]
Maybe this behavior is related/fixed in this commit?

https://github.com/DataDog/datadog-agent/pull/19976

**Comment by IvanTopolcic** [comment]
Thanks for the issue and sorry for the grief!

I don't think it's related necessarily -- that PR was due to internal debugging logic that was removed (also, that PR is merged and deployed, so it's actually in the latest tag, which you're still seeing problems with).

Can you actually do another test and confirm whether or not beta7 also has this issue? And if possible, would you be able to provide a minimal reproducer of this issue?

**Comment by abarone-btf** [comment]
Hi @IvanTopolcic !, thanks for the reply 🙌 .

Of course!, right now am watching the logs using beta7 to test them out, after some hours of testing I will reply with the result. One thing I can assure is that the agent logs of `tls: failed to verify certificate: x509: certificate signed by unknown authority` are constantly appearing (thing that does not happend with previous beta versions).

My application is a nest applicacion deployed in a cloud run container, part of my Dockerfile is as follow:
```
...some installations like  apt-get install python3 make gcc build-essential and npm ci...

RUN npm run build

COPY --from=datadog/serverless-init:beta7 /datadog-init /usr/src/app/datadog-init

RUN bash -c "mkdir /var/task"

COPY datadog.yaml /var/task/datadog.yaml

ENV NODE_OPTIONS="--require dd-trace/init"

RUN chown -R node:node /usr/src/app

USER node

ENTRYPOINT ["/usr/src/app/datadog-init"]

CMD [ "node", "dist/apps/public/main" ]
```

Here are some agent logs
<img width="1345" alt="image" src="https://github.com/DataDog/datadog-agent/assets/133253254/601c502d-bbd8-4187-b4d3-e0d05a653e2e">

Thanks again for your help

**Comment by IvanTopolcic** [comment]
To me that would mean something is happening to your system certificates which lead it to be unable to verify our certificate, which causes the request to fail. That's likely the reason you're not able to see logs -- as the request is never made to Datadog.

In general, we see this error with users who use older linux distros who don't update their system certs. I'm not entirely sure why this would happen in the middle of your application lifecycle. Are you somehow mutating your system certs while the application is running?

**Comment by IvanTopolcic** [comment]
One more thing, do you see those x509 cert failures even when you're getting logs correctly? Or do they only show up once logs stop coming in to Datadog?

**Comment by abarone-btf** [comment]
Nop!, we are not changing any configuration of certificates in our application, we keep almost everything as the cloud run default ("almost" with some configuration to just receive traffic from a load balancer and that kind of stuff).

We are currently using a pinned node version on our Dockerfile which points to 18.18.0-buster-slim, do you think it can be that?.

About the x509 message, it constantly appears on the logs even when the logs are appearing on the Cloud Logging page, I commented about the message because it bring my attention knowing that older beta versions don't show them, but maybe it has nothing to do with the problem itself.

Some more images of the agent logs:
<img width="1345" alt="image" src="https://github.com/DataDog/datadog-agent/assets/133253254/fff611dc-5180-467a-a4e1-e7508c78e29b">

<img width="1345" alt="image" src="https://github.com/DataDog/datadog-agent/assets/133253254/979c39a9-575f-46e5-bd15-8f0b00582ff1">

**Comment by IvanTopolcic** [comment]
Okay I see, that makes sense. And to clarify, when the logs disappear, you don't see them in the Cloud Run console, **as well as** Datadog Logs, correct?

**Comment by abarone-btf** [comment]
Perfect!, I will do one with the latest version of the serverless-init, to check if the logs dissapear again (and also to check the warning message of x509) 🙌

**Comment by abarone-btf** [comment]
I test the `ca-certificates` and the logs are now never dissapearing, plus the logs of x509 never appeared again 🚀 . Right now am only seeing this warn messages (the only one "similar" to the x509 is the `Could not send payload: Post "https://http-intake.logs.datadoghq.com/api/v2/logs": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`, but it only appeared once so I think it was a normal behavior which was retried or something):

<img width="965" alt="image" src="https://github.com/DataDog/datadog-agent/assets/133253254/323e19f1-4701-42dd-a57a-11f582506a22">


Dont know why `DD_APPSEC_ENABLED` is an unknown env variable 🤔 , is that normal?. Thanks again for everything!

**Comment by IvanTopolcic** [comment]
I'd remove `DD_APPSEC_ENABLED` as it's not supported in serverless-init.

**Comment by IvanTopolcic** [comment]
As for the fix to this issue, we're currently looking at a way to avoid serverless-init swallow application logs when the buffer fills up as this could happen when our backend goes down, which would cause missing application logs, which is 🚫

**Comment by nhulston** [comment]
Closing this issue because it is outdated. If you are still facing this issue, please view the [updated docs](https://docs.datadoghq.com/serverless/google_cloud_run/jobs/) and feel free to open a new issue. Thank you
