### ISSUE TITLE
system probe error: failed to delete mountpoint from cache <id> unknown mount id

### ISSUE THREAD

**Issue by william-salt-cko** [DataDog/datadog-agent#7073]
**Describe what happened:**
I've recently enabled sysprobe on an estate and get regular errors for files stating:
```
(pkg/security/probe/probe_bpf.go:343 in handleMountEvent) | failed to delete mount point 1394 from cache: unknown mount ID
```

**Describe what you expected:**
I would expect the mount event to be picked up and inserted into the cache, and no errors to occur when getting a umount event. 

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**
latest version 6.24.1

**Comment by cp-jennifer** [comment]
Did you ever get around to figuring this out? I'm running into the same issue and it's causing my system-probe container to restart hundreds of times due to OOMKills. I'm running datadog-agent version 7.25.0 and kube version 1.14.8.

**Comment by william-salt-cko** [comment]
@cp-jennifer I didn't. I am presuming that either the cache doesn't have a file in it because it was there before datadog started and the cache isn't hydrated on startup, or the caching logic is flawed. I didn't have a chance to dig into the code and make a fix. I presumed it would get fixed in later versions as this feature is pretty beta. Instead, I am ignoring these errors and using the exporter.

**Comment by cp-jennifer** [comment]
@william-salt-cko Gotcha, thanks for letting me know! FWIW, I tested the latest version of the agent (7.25.0) and although it solved my other system-probe issues (container restarting hundreds of times from OOMKills), this issue still remains. Hopefully, Datadog will have a fix for this soon.

**Comment by safchain** [comment]
We changed the log level from Error to Warn in the 7.26 version. The log level was incorrect regarding the severity of this.

**Comment by safchain** [comment]
Closing it for now, feel free to re-open if you still see the error with more recent versions.
